import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  standalone: true,
  template: `<main><header><a href="#home">DC / ENGINEERING</a><nav><a href="#work">Work</a><a href="#experience">Experience</a><a href="#about">About</a><a href="#contact">Contact</a></nav><a class="resume" href="#contact">Resume ↗</a></header><section id="home" class="hero"><p class="mono">BACKEND ENGINEER / SOFTWARE ARCHITECT</p><h1>Building systems<br><span>that hold up.</span></h1><p class="intro">I design scalable APIs, distributed systems and reliable infrastructure for products people depend on.</p><a class="button" href="#work">View selected work ↓</a></section><section id="work" class="section"><div class="eyebrow mono">01 / SELECTED WORK</div><div class="project"><div><span class="tag mono">SOCIAL COMMERCE</span><h2>Reals Platform</h2><p>High-performance social commerce platform with identity, media processing and event-driven services.</p></div><span class="project-arrow">↗</span></div><div class="project"><div><span class="tag mono">DATA PLATFORM</span><h2>Commerce Signals</h2><p>Reliable ingestion and reporting infrastructure designed for large data volumes and clear decisions.</p></div><span class="project-arrow">↗</span></div></section><section id="experience" class="split"><div><div class="eyebrow mono">02 / EXPERTISE</div><h2>Strong foundations.<br><span>Quiet complexity.</span></h2></div><div class="skills"><p><b>Backend</b> Node.js · NestJS · TypeScript</p><p><b>Data</b> PostgreSQL · Redis · Prisma</p><p><b>Systems</b> Events · Queues · Observability</p><p><b>Delivery</b> Docker · CI/CD · Cloud</p></div></section><section id="about" class="about"><div class="eyebrow mono">03 / ABOUT</div><h2>Make it clear.<br>Make it last.</h2><p>I care about useful abstractions, measurable performance and systems that remain understandable as they grow.</p></section><section id="contact" class="contact"><div class="eyebrow mono">04 / CONTACT</div><h2>Have a hard<br><span>problem?</span></h2><a class="button" href="mailto:hello@example.com">Let's talk ↗</a></section><footer><span>DC / ENGINEERING</span><span class="mono">© 2026</span></footer></main>`,
  styles: [`:host{display:block}main{min-height:100vh;background:#101312;color:#e8eee8}header{height:76px;display:flex;align-items:center;justify-content:space-between;padding:0 6vw;border-bottom:1px solid #2a302b}header a{color:inherit;text-decoration:none;font-size:.7rem}.mono{font-family:'DM Mono',monospace;font-size:.68rem;letter-spacing:.08em;color:#9eb99e}nav{display:flex;gap:28px}.resume,.button{padding:11px 15px;border:1px solid #789b78;border-radius:3px}.hero,.section,.split,.about,.contact{padding:12vw 14vw}.hero{min-height:calc(100vh - 76px);display:flex;flex-direction:column;justify-content:center}.hero h1{margin:24px 0;font-size:clamp(4rem,10vw,10rem);font-weight:600;letter-spacing:-.09em;line-height:.88}.hero h1 span,h2 span{color:#b9d66e}.intro,.project p,.about p{max-width:470px;color:#9aa49b;line-height:1.7}.button{display:inline-block;margin-top:25px;color:#101312;background:#b9d66e;text-decoration:none;font-size:.75rem}.section{background:#171c18}.eyebrow{margin-bottom:55px}.project{display:flex;justify-content:space-between;gap:30px;padding:34px 0;border-top:1px solid #39423a}.project h2{margin:14px 0;font-size:clamp(2rem,4vw,4rem);font-weight:500;letter-spacing:-.07em}.tag{color:#b9d66e}.project-arrow{font-size:2rem;color:#b9d66e}.split{display:grid;grid-template-columns:1fr 1fr;gap:10vw}.split h2,.about h2,.contact h2{font-size:clamp(3rem,6vw,6rem);font-weight:500;letter-spacing:-.08em;line-height:.9}.skills{border-top:1px solid #39423a}.skills p{padding:17px 0;border-bottom:1px solid #39423a;color:#9aa49b}.skills b{display:inline-block;width:100px;color:#e8eee8}.about{background:#b9d66e;color:#101312}.about .eyebrow,.about p{color:#344333}.contact{background:#ed694e}.contact .eyebrow{color:#f6d4cb}.contact h2 span{color:#f4e8d6}footer{display:flex;justify-content:space-between;padding:25px 6vw;color:#7e8b80;font-size:.7rem}@media(max-width:700px){header{padding:0 20px}nav{display:none}.hero,.section,.split,.about,.contact{padding:90px 24px}.split{display:block}.skills{margin-top:50px}.project{gap:10px}.project-arrow{font-size:1.4rem}}
`] 
})
export class AppComponent {}
